taskkill /f /im RankingDaemon.exe
taskkill /f /im AccountInventoryDaemon.exe
taskkill /f /im CacheDaemon.exe
taskkill /f /im CacheGate.exe
taskkill /f /im PostOfficeDaemon.exe
taskkill /f /im LobbyDaemon.exe
taskkill /f /im CraftDaemon.exe
taskkill /f /im MarketReaderDaemon.exe
taskkill /f /im MarketDealerAgent.exe
taskkill /f /im MarketDealerDaemon.exe
taskkill /f /im MarketReaderAgent.exe
taskkill /f /im ArenaLobby.exe
taskkill /f /im AchievementDaemon.exe
taskkill /f /im DuelBotDaemon.exe
taskkill /f /im GameDaemon.exe
taskkill /f /im InfoGateDaemon.exe
taskkill /f /im LobbyGate.exe