CREATE DATABASE CouponSystemDB;
GO
USE CouponSystemDB;
GO

CREATE TABLE PromoIssues (
  IssueId INT IDENTITY PRIMARY KEY,
  IssueName NVARCHAR(200) NOT NULL,
  RedeemFrom DATETIMEOFFSET NULL,
  RedeemTo DATETIMEOFFSET NULL,
  EffectiveFrom DATETIMEOFFSET NULL,
  EffectiveTo DATETIMEOFFSET NULL,
  ExpirationDuration INT NULL, -- дни
  CreatedAt DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE PromoCoupons (
  CouponId INT IDENTITY PRIMARY KEY,
  IssueId INT NOT NULL FOREIGN KEY REFERENCES PromoIssues(IssueId) ON DELETE CASCADE,
  CouponCode NVARCHAR(100) NOT NULL UNIQUE,
  MaxUses INT NOT NULL DEFAULT 1,
  UsedCount INT NOT NULL DEFAULT 0,
  CreatedAt DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()
);

CREATE TABLE PromoRewards (
  RewardId INT IDENTITY PRIMARY KEY,
  IssueId INT NOT NULL FOREIGN KEY REFERENCES PromoIssues(IssueId) ON DELETE CASCADE,
  ItemID INT NOT NULL,
  Quantity INT NOT NULL DEFAULT 1,
  RewardName NVARCHAR(200) NULL
);

CREATE TABLE PromoActivations (
  ActivationId INT IDENTITY PRIMARY KEY,
  CouponId INT NOT NULL FOREIGN KEY REFERENCES PromoCoupons(CouponId) ON DELETE CASCADE,
  UserId UNIQUEIDENTIFIER NOT NULL,
  ActivatedAt DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()
);
GO
